# Question 1:


In [61]:
import numpy as np
x = np.array([1,2,3,4,5,6])
li = x.tolist()
li

[1, 2, 3, 4, 5, 6]

# Question 2:

In [80]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
sum = 0
for i in range(0,(a.shape[0])):
    for j in range(0,(a.shape[1])):
        if i==j:
            sum +=a[i,j]
print(a)
print(sum)
            

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)
34


# Question 3:


In [81]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
x=5
for i in range(0,(a.shape[0])):
    for j in range(0,(a.shape[1])):
        if a[i,j] > x:
            print(a[i,j])

6
7
8
9


# Question 4:


In [82]:
A = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
B = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
C = A + B
print(C)

[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]]


# Question 5:

In [93]:
Arr = np.array([[5,5,8,5],[9,8,3,6],[4,2,4,9]])
print(Arr)
print(Arr.shape)
mean = 0
for i in range(0,Arr.shape[0]):
    sum = 0
    for j in range(0,Arr.shape[1]):
        sum+=Arr[i,j]
    mean = sum / Arr.shape[1]
    print("The mean of the", i , "row is" , mean)

[[5 5 8 5]
 [9 8 3 6]
 [4 2 4 9]]
(3, 4)
The mean of the 0 row is 5.75
The mean of the 1 row is 6.5
The mean of the 2 row is 4.75
